### PR TITLE
Restore support for OpenSSL 1.0.1

### LINKED ISSUE #2: Build fails with OpenSSL 1.0.1
Commit c4dd98d88736af0b479d3b17c8cc35646a2a1ea8 broke compatibility with OpenSSL 1.0.1:

```
cc -I/usr/include -fPIC -Wall -Werror -g   -c -o danessl.o danessl.c
cc1: warnings being treated as errors
danessl.c: In function 'DANESSL_verify_chain':
danessl.c:1172: error: implicit declaration of function 'SSL_is_server'
danessl.c:1174: error: implicit declaration of function 'SSL_get0_param'
danessl.c:1174: error: passing argument 2 of 'X509_VERIFY_PARAM_set1' makes pointer from integer without a cast
/usr/include/openssl/x509_vfy.h:516: note: expected 'const struct X509_VERIFY_PARAM *' but argument is of type 'int'
make: *** [danessl.o] Error 1
```

### PR DESCRIPTION
**Pull request by ErwanLegrand**
dane_ssl would not build with OpenSSL 1.0.1

Fixes #2

### CODE REVIEW

**Comment by vdukhovni** [comment]
Thanks for the report. Fixed in d9767f2fc78dbaf990c18df00bf17fd0c2ee2baa
